// Sample Developers Data (Replace with your API later)

export const developers = [
  {
    id: 1,
    name: "Anas Malik",
    photo: "/ProfilePic.jpg",
    skills: ["React", "Next.js", "TypeScript", "Node.js"],
    experience: 5,
    hourlyRate: 1200,
    availability: "Full-time",
    rating: 4.9,
    level: "Expert",
  },
  {
    id: 2,
    name: "Priya Mehta",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    skills: ["Flutter", "Dart", "Firebase", "Android"],
    experience: 4,
    hourlyRate: 950,
    availability: "Part-time",
    rating: 4.8,
    level: "Beginner",
  },
  {
    id: 3,
    name: "Rohan Kapoor",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    skills: ["Laravel", "PHP", "MySQL", "Vue.js"],
    experience: 6,
    hourlyRate: 800,
    availability: "Project-basis",
    rating: 4.7,
    level: "Expert",
  },
  {
    id: 4,
    name: "Ananya Singh",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    skills: ["React Native", "Node.js", "MongoDB", "AWS"],
    experience: 3,
    hourlyRate: 1100,
    availability: "Full-time",
    rating: 5.0,
    level: "Intermediate",
  },
  {
    id: 5,
    name: "Vikram Patel",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    skills: ["Python", "Django", "FastAPI", "PostgreSQL"],
    experience: 7,
    hourlyRate: 1500,
    availability: "Full-time",
    rating: 4.9,
    level: "Expert",
  },
  {
    id: 6,
    name: "Neha Verma",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    skills: ["Angular", "TypeScript", "NestJS", "Docker"],
    experience: 4,
    hourlyRate: 1050,
    availability: "Part-time",
    rating: 4.6,
    level: "Intermediate",
  },
];